### ISSUE TITLE
Joomla Extension Directory Update

### ISSUE THREAD

**Issue by tablighdotat** [PavelSyomin/flexi_custom_code#1]
Hi Pavel Syomin,

Could you please add a note nd tag of J5 to the extension's description in the Joomla Extensions Directory stating that it is compatible with J5 too and can be installed?
(I'm using J5 with PHP version 8.2 and haven't had any issues so far.)

This extension is the best option for replacing the module edit view for custom PHP code, and I've given it 5 stars and written a positive review.
However, when I recommend it to others, they ask if it's only compatible with Joomla 4 and if it hasn't been updated for Joomla 5 yet.

And please, if you want, add your website or ways to contact you in your profile, the only place I was able to contact you was GitHub and I hope I put it in the right place.

Thank you for supporting the Joomla community

**Comment by PavelSyomin** [comment]
Hi,
I am going to check the Joomla 5 support in the next two weeks, and if everything is OK, I'll add the v5 tag to JED.
This GitHub is the right place to contact me :)

**Comment by PavelSyomin** [comment]
Hi again,
I've tested this extension on J5 and found out that it works correctly. So I've added the respective tag on JED.
